remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache   # ← add this

title: Esteban Flores
description: Robotics • Test • Prototyping
url: ""
baseurl: ""
minimal_mistakes_skin: "dark"